spring:
  data:
    mongodb:
      database: library
  mongodb:
    embedded:
      version: 5.0.0
mongock:
  runner-type: "ApplicationRunner" # default
  #runner-type: "InitializingBean"
  change-logs-scan-package:
    - org.kivilev.mongock.changelog
  enabled: false