version: "3.9"
services:
  mongo:
    image: mongo:6.0.5
    restart: always
    container_name: hw11-mongo-docker
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
      MONGO_INITDB_DATABASE: library
    networks:
      - hw11

  mongo-express:
    image: mongo-express
    container_name: hw11-mongo-express
    restart: always
    ports:
      - 8090:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      ME_CONFIG_MONGODB_URL: mongodb://root:example@mongo:27017/
    networks:
      - hw11

  hw11-mvc:
    build: .
    depends_on:
      - mongo
    ports:
      - "9000:8080"
    restart: unless-stopped
    environment:
      SPRING_DATASOURCE_URL: mongodb://root:example@mongo:27017/
    networks:
      - hw11

networks:
  hw11: